title: Fichier

sections:
  content:
    type: fields
    fields:
      caption:
        label: Légende
        type: markdown
      alt:
        label: Alternative textuelle
        type: text
      is_big:
        label : Grande taille ?
        type: toggle
        text:
          - Non
          - Oui